### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by douglasdeodato** [riwakawebsitedesigns/htaccess_for_codeigniter#1]
hello nice tutorial,

i tried but no sucess :(, 

i just got confuse that .htaccess should be out of application right? and i can't change the one in application folder right?

which one you can indicate for : Ubuntu 14.04.2 LTS (GNU/Linux 4.0.2-x86_64-linode56 x86_64)

thanks

**Comment by tasmanwebsolutions** [comment]
The .htaccess should be in main directory do not touch the .htaccess that is in application folder. Also I do not know which is best for Linux servers if you know of any please add as pull request
